# Generated by Django 3.1.4 on 2020-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_id', models.CharField(max_length=64, verbose_name='行政机关代码')),
                ('adm_name', models.CharField(max_length=64, verbose_name='机关名称')),
                ('adm_province', models.CharField(max_length=64, verbose_name='所属省份')),
                ('adm_city', models.CharField(max_length=64, verbose_name='所在市')),
                ('adm_district', models.CharField(max_length=64, verbose_name='所在区')),
                ('adm_location', models.CharField(max_length=128, verbose_name='详细地址')),
                ('adm_tel', models.CharField(max_length=64, verbose_name='联系电话')),
                ('adm_mail', models.CharField(max_length=64, verbose_name='邮箱')),
                ('adm_level', models.SmallIntegerField(choices=[(1, '县级'), (2, '市级'), (4, '最高检'), (0, '区级'), (3, '省级')], verbose_name='层级')),
            ],
            options={
                'verbose_name': '行政机关信息',
                'verbose_name_plural': '行政机关信息',
            },
        ),
        migrations.CreateModel(
            name='Procuratorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=64, verbose_name='检察院代码')),
                ('org_name', models.CharField(max_length=64, verbose_name='检察院名称')),
                ('org_province', models.CharField(max_length=64, verbose_name='所属省份')),
                ('org_city', models.CharField(max_length=64, verbose_name='所在市')),
                ('org_district', models.CharField(max_length=64, verbose_name='所在区')),
                ('org_address', models.CharField(max_length=128, verbose_name='详细地址')),
                ('org_tel', models.CharField(max_length=64, verbose_name='联系电话')),
                ('org_mail', models.CharField(max_length=64, verbose_name='邮箱')),
                ('org_level', models.SmallIntegerField(choices=[(1, '县级'), (2, '市级'), (4, '最高检'), (0, '区级'), (3, '省级')], verbose_name='检察院层级')),
            ],
            options={
                'verbose_name': '检察院信息',
                'verbose_name_plural': '检察院信息',
            },
        ),
    ]
