# Generated by Django 3.1.4 on 2020-12-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_auto_20201218_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64, verbose_name='案件编号')),
                ('case_title', models.CharField(max_length=128, verbose_name='案件标题')),
                ('case_description', models.TextField(verbose_name='案情描述')),
                ('case_status', models.SmallIntegerField(choices=[(0, '立案'), (1, '检察建议阶段'), (2, '整改计划阶段'), (3, '整改报告阶段'), (4, '评估阶段'), (5, '办理完毕')], default=0, verbose_name='办理状态')),
                ('case_type', models.CharField(max_length=64, verbose_name='案件类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='立案时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('case_decision', models.SmallIntegerField(blank=True, choices=[(0, '起诉'), (1, '不起诉')], null=True, verbose_name='处理决定')),
                ('case_object', models.ManyToManyField(related_name='object', to='organization.Administration', verbose_name='涉案机构')),
                ('case_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='organization.procuratorate', verbose_name='办案机构')),
            ],
            options={
                'verbose_name': '案件信息',
                'verbose_name_plural': '案件信息',
            },
        ),
    ]
