# Generated by Django 3.1.3 on 2020-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201209_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSuggestionUnstructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc_ID', models.CharField(max_length=128, verbose_name='文书号')),
                ('Doc_Title', models.CharField(max_length=128, verbose_name='文书标题')),
                ('Doc_Creator', models.CharField(max_length=128, verbose_name='创建者')),
                ('Doc_Sender', models.CharField(max_length=128, verbose_name='发送者')),
                ('Doc_Content', models.TextField(verbose_name='文书内容')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('send_time', models.DateField(verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '非结构化检察建议',
                'verbose_name_plural': '非结构化检察建议',
            },
        ),
    ]
