# Generated by Django 3.1.4 on 2020-12-18 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sug_id', models.CharField(max_length=64, verbose_name='文书号')),
                ('sug_title', models.CharField(max_length=128, verbose_name='文书标题')),
                ('sug_content', models.TextField(verbose_name='文书内容')),
                ('sug_status', models.SmallIntegerField(choices=[(0, '创建'), (1, '保存'), (2, '审核'), (3, '发送'), (4, '回复'), (5, '归档')], verbose_name='文书状态')),
                ('sug_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sug_last_edit', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('sug_edit_times', models.IntegerField(default=1, verbose_name='编辑次数')),
                ('sug_reply_content', models.TextField(verbose_name='评价意见')),
                ('sug_reply_time', models.DateTimeField(auto_now=True, null=True)),
                ('sug_create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('sug_last_edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_editor', to=settings.AUTH_USER_MODEL, verbose_name='最近一次修改者')),
                ('sug_reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_reply', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '文书统一信息',
                'verbose_name_plural': '文书统一信息',
            },
        ),
        migrations.CreateModel(
            name='DocReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_id', models.CharField(max_length=64, verbose_name='文书号')),
                ('rep_title', models.CharField(max_length=128, verbose_name='文书标题')),
                ('rep_content', models.TextField(verbose_name='文书内容')),
                ('rep_status', models.SmallIntegerField(choices=[(0, '创建'), (1, '保存'), (2, '审核'), (3, '发送'), (4, '回复'), (5, '归档')], verbose_name='文书状态')),
                ('rep_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rep_last_edit', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('rep_edit_times', models.IntegerField(default=1, verbose_name='编辑次数')),
                ('rep_reply_content', models.TextField(verbose_name='评价意见')),
                ('rep_reply_time', models.DateTimeField(auto_now=True, null=True)),
                ('rep_create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('rep_last_edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_editor', to=settings.AUTH_USER_MODEL, verbose_name='最近一次修改者')),
                ('rep_reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_reply', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '整改报告文书',
                'verbose_name_plural': '整改报告文书',
            },
        ),
        migrations.CreateModel(
            name='DocPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=128, verbose_name='文书标题')),
                ('plan_content', models.TextField(verbose_name='文书内容')),
                ('plan_status', models.SmallIntegerField(choices=[(0, '创建'), (1, '保存'), (2, '审核'), (3, '发送'), (4, '回复'), (5, '归档')], verbose_name='文书状态')),
                ('plan_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plan_last_edit', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('plan_edit_times', models.IntegerField(default=1, verbose_name='编辑次数')),
                ('plan_reply_content', models.TextField(verbose_name='评价意见')),
                ('plan_reply_time', models.DateTimeField(auto_now=True, null=True)),
                ('plan_edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_editor', to=settings.AUTH_USER_MODEL, verbose_name='最近一次修改者')),
                ('plan_reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_reply', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('plan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '整改计划文书',
                'verbose_name_plural': '整改计划文书',
            },
        ),
    ]
